name: Publish package to the Maven Central Repository
on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ release ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        env:
          NEXUS2_USERNAME: ${{ secrets.NEXUS2_USERNAME }}
          NEXUS2_PASSWORD: ${{ secrets.NEXUS2_PASSWORD }}
          GPG_PASSPHRASE:  ${{ secrets.GPG_PASSPHRASE }}
          GPG_SECRET_KEY:  ${{ secrets.GPG_SECRET_KEY }}
          GPG_PUBLIC_KEY:  ${{ secrets.GPG_PUBLIC_KEY }}
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw clean install package deploy